// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlpdytiekebbyanagpon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5scGR5dGlla2ViYnlhbmFncG9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDE2NTIsImV4cCI6MjA2NDM3NzY1Mn0.7b8BPK-LS4U86cNkEqHnFAMuqSv63_HmM-hjo5g4E8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);